name: Docker CI

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nginx-devops-project:ci .

      - name: Run Nginx container
        run: docker run -d -p 8081:80 --name nginx-test nginx-devops-project:ci

      - name: Test Nginx application
        run: curl --fail http://localhost:8081
